CREATE TABLE IF NOT EXISTS star_records (
  record_id VARCHAR(100) PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  type ENUM('income', 'expense') NOT NULL,
  source VARCHAR(50) NOT NULL,
  source_id VARCHAR(100) DEFAULT NULL,
  points INT NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  expiry_type VARCHAR(50) DEFAULT NULL,
  expiry_date VARCHAR(20) DEFAULT NULL,
  balance INT DEFAULT 0,
  previous_balance INT DEFAULT 0,
  original_task_date VARCHAR(20) DEFAULT NULL,
  requested_points INT DEFAULT NULL,
  idempotency_key VARCHAR(150) DEFAULT NULL,
  data JSON DEFAULT NULL,
  modify_time BIGINT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  INDEX idx_star_records_user_id (user_id),
  INDEX idx_star_records_source_id (source_id),
  INDEX idx_star_records_created_at (created_at),
  UNIQUE KEY uk_star_records_idempotency_key (idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
