CREATE TABLE IF NOT EXISTS rewards (
  reward_id VARCHAR(100) PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  family_id VARCHAR(100) DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  type VARCHAR(50) DEFAULT 'item',
  points INT NOT NULL,
  icon VARCHAR(50) DEFAULT NULL,
  enabled TINYINT(1) DEFAULT 1,
  claimed TINYINT(1) DEFAULT 0,
  claim_time BIGINT DEFAULT NULL,
  claim_status VARCHAR(50) DEFAULT 'available',
  delivery_time BIGINT DEFAULT NULL,
  exchange_user_id VARCHAR(100) DEFAULT NULL,
  is_example TINYINT(1) DEFAULT 0,
  tags JSON DEFAULT NULL,
  notes TEXT,
  protected_by_expiry TINYINT(1) DEFAULT 0,
  partial_protection INT DEFAULT 0,
  modify_time BIGINT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  INDEX idx_rewards_user_id (user_id),
  INDEX idx_rewards_family_id (family_id),
  INDEX idx_rewards_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
